### ISSUE TITLE
no matches, but characters are in `chars.txt` ? [java]

### ISSUE THREAD

**Issue by emilburzo** [codebox/homoglyph#11]
Hi, first off, amazing library! thanks for putting this together

The test code from the README works perfectly, but I have an issue when trying it with some real user input:

```
class Scratch {
    public static void main(String[] args) throws IOException {
        String textToSearch = "ᑕᒪᑌᗷ";
        String[] bannedWords = new String[]{"club"};
        Homoglyph homoglyph = HomoglyphBuilder.build();
        List<Homoglyph.SearchResult> results = homoglyph.search(textToSearch, bannedWords);
        System.out.println(results.size());
    }
}
```

(in case it's not visible in github: the letters should be: `\N{CANADIAN SYLLABICS TA}\N{CANADIAN SYLLABICS MA}\N{CANADIAN SYLLABICS TE}\N{CANADIAN SYLLABICS CARRIER KHE}`)

This returns 0 matches, even though I can find all the characters in https://github.com/codebox/homoglyph/blob/master/raw_data/chars.txt

What am I missing?

**Comment by emilburzo** [comment]
One thing I noticed is that `CANADIAN SYLLABICS TA` (`ᑕ`) is on line https://github.com/codebox/homoglyph/blob/master/raw_data/chars.txt#L477, but I would expect it to be on line https://github.com/codebox/homoglyph/blob/master/raw_data/chars.txt#L42

**Comment by emilburzo** [comment]
Got it, this mapping was missing in `confusables_extras.txt`:

```
1455 ; 0043 ; MA  # CANADIAN SYLLABICS TA → LATIN CAPITAL LETTER C
```

**Comment by codebox** [comment]
thanks, I've updated the code with this mapping
