### ISSUE TITLE
Merge 'x' lists

### ISSUE THREAD

**Issue by cdalexndr** [codebox/homoglyph#5]
Should the following two generated lists be merged?
```
x×хᕁᕽ᙮ⅹ⤫⤬⨯ｘ𝐱𝑥𝒙𝓍𝔁𝔵𝕩𝖝𝗑𝘅𝘹𝙭𝚡
XΧХ᙭ᚷⅩ╳ⲬⵝꓫꞳＸ𐊐𐊴𐌗𐌢𐔧𑣬𝐗𝑋𝑿𝒳𝓧𝔛𝕏𝖃𝖷𝗫𝘟𝙓𝚇𝚾𝛸𝜲𝝬𝞦
```

**Comment by Isopach** [comment]
In my opinion, no. 
Because the small x and capital X are two different characters.

**Comment by codebox** [comment]
It shouldn't matter that they are separate lists, the code checks both upper and lower case version of each character.
