### ISSUE TITLE
lowercase L to capital i homoglyph

### ISSUE THREAD

**Issue by emschorsch** [codebox/homoglyph#9]
In the generated confusables table there is conversion from lowercase L to capital I. In for example Intel vs lntel. I couldn't figure out how to modify the generator to include this homoglyph. Any ideas?

**Comment by codebox** [comment]
The simplest way is to add a new line to confusables_extras.txt, something like this (not tested):
`49 ; 6c ; MA	# ( I → l )`
49 and 6c are the hex codes for the 2 letters, the 'MA' part has to be there for reasons that the Unicode docs are vague about, and the #... is just a comment
